# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  version: 2.2.3


steps:

- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: publish
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: "-c Release -o $(Build.ArtifactStagingDirectory)/drop"
    projects: '**/*.csproj'
    zipAfterPublish: true
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/drop'
  displayName: "Publish drop"

- task: CmdLine@2
  displayName: az login
  inputs:
    script: |
      az login
- task: UniversalPackages@0
  displayName: Push to UP
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactStagingDirectory)/drop'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: '2d490202-a003-4888-b45c-70ea12d8bb2c/e6c13509-597e-4ec3-b967-280e212d8945'
    vstsFeedPackagePublish: 'my-first-package'    
    versionOption: 'custom'
    versionPublish: $(version)
    packagePublishDescription: 'test'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)/drop'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/drop2'
  

