# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'


steps:

- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: publish
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: "-c Release -o $(Build.ArtifactStagingDirectory)/drop"
    projects: '**/*.csproj'
    zipAfterPublish: true
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/drop'
  displayName: "Publish drop"
- task: CmdLine@2
  inputs:
    script: |
      az artifacts universal publish --organization https://dev.azure.com/MatZajOrg/ --project="Demo" --scope project --feed my-test-feed --name my-first-package --version 0.0.1 --description "Welcome to Universal Packages" --path $(Build.ArtifactStagingDirectory)/drop

